# **NUMPY FOUNDATIONS**

##BASIC FUNCTIONS

In [4]:
# Importing numpy as np , np is just a shortform which we will use in the notebook instead of writing "numpy"
import numpy as np

In [5]:
# How 1D array is made using numpy:
array_1d = np.array([1,2,3,4])
print(f"array_1d looks like: {array_1d}")
print(f"dtype of array_1d: {type(array_1d)}")

array_1d looks like: [1 2 3 4]
dtype of array_1d: <class 'numpy.ndarray'>


In [6]:
# 2D and 3D arrays using np
array_2d = np.array([[1,2],[3,4]])
print(f"array_2d looks like:\n{array_2d}")
print(f"dtype of array_2d: {type(array_2d)}. Same as array_1d")

array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,2]]])
print(f"array_3d looks like:\n{array_3d}")
print(f"dtype of array_3d: {type(array_3d)}. Same as array_1d")


array_2d looks like:
[[1 2]
 [3 4]]
dtype of array_2d: <class 'numpy.ndarray'>. Same as array_1d
array_3d looks like:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 2]]]
dtype of array_3d: <class 'numpy.ndarray'>. Same as array_1d


In [7]:
# np.arange function -> works like range function which require 2 values , 1st value is included and 2nd is exclused in output array.
print("printing the output without storing it in variable:")
np.arange(1,11)

printing the output without storing it in variable:


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print("After storing it in arange_variable:")
arange_variable = np.arange(1,11)
print (f"arange_variable:\n {arange_variable}")
print("See, 1 is included in array but 11 is excluded, number before 11 is included.")

After storing it in arange_variable:
arange_variable:
 [ 1  2  3  4  5  6  7  8  9 10]
See, 1 is included in array but 11 is excluded, number before 11 is included.


In [9]:
# using dtype
np.arange(1,11,dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
# arange with steps
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
# arange with single value (it starts with 0 when positive number and [] when single negative value is given)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [13]:
# with reshape -> .reshape() helps in reshaping the numpy array with valid input. If input for .reshape is (3,3) it means reshaping array in 3x3 array or matrix.
# np.arange(1,11) include 10 values, using reshape function we can reshape the array in (2,5)...(5,2)... but we can't reshape it as (3,4)
# because 3x4 matrix include 12 values and here we have only 10.
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
# arange with reshape example
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [15]:
"""Initialising Array using np.zeros , np.ones and np.random"""

# np.ones and np.zeros
# np.ones need shape as input OR here, we provide the 'tuple'
ones_variable = np.ones((2,3))
print(f"ones_variable:\n{ones_variable}\n")

zeros_variable = np.zeros((4,5))
print(f"zeros_variable:\n{zeros_variable}\n")

print("USECASE: intializing weights in neural networks")

ones_variable:
[[1. 1. 1.]
 [1. 1. 1.]]

zeros_variable:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

USECASE: intializing weights in neural networks


In [16]:
# np.random -> initialize with random values between 0 and 1
np.random.random((3,4))

# why two randoms? -> because random is a class and it has a method named random ( concept of OOPS )

array([[0.23885813, 0.5431331 , 0.48745904, 0.17255395],
       [0.01259603, 0.02255157, 0.18755035, 0.96711094],
       [0.22552979, 0.70664578, 0.12211101, 0.73831245]])

In [17]:
# np.linspace -> helps in generating the values within a range where lowerbound and upperbound are inclusive/included.
# ALSO, all the elements generated are linearly gapped
# np.linspace(lowerbound, upperbound, number of elements)
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [18]:
# np.identity -> helps creating identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## ARRAY ATTRIBUTES:
We know that every np array is a object of numpy class.
So, attributes are properties of NumPy arrays that provide information about the array's shape, size, data type, dimension, and so on

In [19]:
# creating 3 arrays for further use
# a1 is a array/vector , a2 is a matrix , a3 is like a tensor or 3D tensor
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [20]:
# printing the a1,a2,a3
print(f"a1:\n{a1}\n")
print(f"a2:\n{a2}\n")
print(f"a3:\n{a3}\n")

a1:
[0 1 2 3 4 5 6 7 8 9]

a2:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

a3:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [21]:
# ndim -> tells the dimension of array
print(f"dimension of a1: {a1.ndim}")
print(f"dimension of a2: {a2.ndim}")
print(f"dimension of a3: {a3.ndim}")

dimension of a1: 1
dimension of a2: 2
dimension of a3: 3


In [22]:
# np.shape -> tells the shape in array

print(f"shape of a1: {a1.shape}")
print(f"shape of a2: {a2.shape}")
print(f"shape of a3: {a3.shape}")

# shape of a1: (10,) means we have 10 items in single direction
# shape of a2: (3, 4) means we have 3 rows and 4 columns
# shape of a3: (2, 2, 2) means there are two 2D arrays of shape 2,2

shape of a1: (10,)
shape of a2: (3, 4)
shape of a3: (2, 2, 2)


In [23]:
# size -> tells how many items
print(f"size of a1: {a1.size}")
print(f"size of a2: {a2.size}")
print(f"size of a3: {a3.size}")

size of a1: 10
size of a2: 12
size of a3: 8


In [24]:
# itemsize -> how much space array is occupying in memory and give output in bytes
# a2 a3 both gave the result '8' because integer and float value usually holds 8bytes in memory (in google colab , both int64(by default) and float hold same size)
# if i change it to int32, it will give 4 as output
print(f"itemsize of a1: {a1.itemsize}")
print(f"itemsize of a2: {a2.itemsize}")
print(f"itemsize of a3: {a3.itemsize}")


print("\nNOTE:int32 take 4bytes and int64 take 8bytes")

itemsize of a1: 4
itemsize of a2: 8
itemsize of a3: 8

NOTE:int32 take 4bytes and int64 take 8bytes


In [25]:
# dtype
print(f"dtype of a1: {a1.dtype}")
print(f"dtype of a2: {a2.dtype}")
print(f"dtype of a3: {a3.dtype}")

dtype of a1: int32
dtype of a2: float64
dtype of a3: int64


## CHANGING DATATYPES

In [26]:
# astype -> change the datatype
a3.astype(np.int32)

# USECASE: we have created an array of float dtype but that array is for storing age so you can change dtype to int32(int64 take much bigger space which we dont need)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

##ARRAY OPERATIONS

In [27]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(f"a1:\n{a1}\n")
print(f"a2:\n{a2}\n")

a1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a2:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



###Scalar Operations

In [28]:
# we can do these arithematic operations like + , - , * , / , % modulus , ** power etc...
# example of multiplication
print(a1 * 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


###Relational Operations

In [29]:
# using relational operators like > < >= <= etc... and it give output as true false
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
a2 == 22

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

###Vector Operations

In [31]:
# Vector operations: doing operations on two arrays
# a1 + a2 possible because of same shape
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [32]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

##Array Functions

In [33]:
a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
a1

array([[61., 55., 61.],
       [ 9.,  1., 27.],
       [23., 26., 43.]])

In [34]:
# We will try to cover all the important mathematical functions , we don't need to cover all of them.

# min/max/sum/prod
# min -> give smallest element of array , max -> give largest element , sum sums all the elements , prod multiply all the elements
print(f"max of a1: {np.max(a1)}\n")
print(f"min of a1: {np.min(a1)}\n")
print(f"sum of a1: {np.sum(a1)}\n")
print(f"prod of a1: {np.prod(a1)}\n")

max of a1: 61.0

min of a1: 1.0

sum of a1: 306.0

prod of a1: 1278787176810.0



In [35]:
# max/min but for each column ( use axis = 0 ) and rows ( use axis = 1)
# this axis thing is applicable to every function
np.max(a1, axis = 0)

array([61., 55., 61.])

In [36]:
np.max(a1,axis = 1)

array([61., 27., 43.])

In [37]:
# mean/median/std/var
print(f"mean of a1: {np.mean(a1)}\n")
print(f"median of a1: {np.median(a1)}\n")
print(f"std of a1: {np.std(a1)}\n")
print(f"var of a1: {np.var(a1)}\n")

mean of a1: 34.0

median of a1: 27.0

std of a1: 20.891252821323196

var of a1: 436.44444444444446



In [38]:
# trignometric fucntions ( we dont use it very often )
np.sin(a1)

array([[-0.96611777, -0.99975517, -0.96611777],
       [ 0.41211849,  0.84147098,  0.95637593],
       [-0.8462204 ,  0.76255845, -0.83177474]])

In [39]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(f"a2 vector:\n{a2}\n")
print(f"a3 vector:\n{a3}\n")

# Dot product condition satisfied! a2 of shape 3,4 and a3 of shape 4,3
a4 = np.dot(a2,a3)
print(f"dot product of a2 and a3:\n{a4}.\n\nShape of a4 is {np.shape(a4)}")

a2 vector:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a3 vector:
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

dot product of a2 and a3:
[[114 120 126]
 [378 400 422]
 [642 680 718]].

Shape of a4 is (3, 3)


In [40]:
# log and exponents
print(np.log(a1))
print()
print(np.exp(a1))

[[4.11087386 4.00733319 4.11087386]
 [2.19722458 0.         3.29583687]
 [3.13549422 3.25809654 3.76120012]]

[[3.10429794e+26 7.69478527e+23 3.10429794e+26]
 [8.10308393e+03 2.71828183e+00 5.32048241e+11]
 [9.74480345e+09 1.95729609e+11 4.72783947e+18]]


In [41]:
# round / floor / ceil
np.round((np.random.random((2,3))*100))

array([[87., 23., 45.],
       [20., 87.,  5.]])

##INDEXING AND SLICING

In [83]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

print(f"a1:\n{a1}\n")
print(f"a2:\n{a2}\n")
print(f"a3:\n{a3}")

a1:
[0 1 2 3 4 5 6 7 8 9]

a2:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a3:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [56]:
# Indexing -> accessing the element of array
# positive indexing ( from left to right ) starts with 0
# negative indexing ( from right to left ) starts with -1
# An nD array is made up of two or more (n-1)D arrays. Example: 3D array is made up of 2 2D arrays.
# An nD array needs n number in input to fetch element. Example: 1D array need 1 value to fetch , 3D array needs 3 values

a1[-1]

np.int64(9)

In [44]:
a2[0]

array([0, 1, 2, 3])

In [46]:
a2[1,2]

np.int64(6)

In [52]:
# indexing in 3d matrix
print(a3,"\n")
# [1,1,0] means in a3 which is made of two 2d arrays , access 1th 2d array and in that go to 1th row 0th column
a3[1,1,0]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 



np.int64(6)

In [53]:
# practice of indexing : fetch 0 from a3
a3[0,0,0]

np.int64(0)

In [57]:
a3[1,1]

array([6, 7])

In [63]:
# SLICING : fetch as many elements YOU REQUIRE ACTUALLY
print("a1 matrix:",a1,"\n")

print(f"Fetching 2 3 4 from a1 using slicing: \n{a1[2:5]}")
# [m:n] where m is included and n is excluded. Both m and n are value of position of element/index.

a1 matrix: [0 1 2 3 4 5 6 7 8 9] 

Fetching 2 3 4 from a1 using slicing: 
[2 3 4]


In [66]:
# fetching first row from a2 and all columns
a2[0,:]

array([0, 1, 2, 3])

In [69]:
print("a2:\n",a2,"\n")
a2[:,0]

a2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



array([0, 4, 8])

In [71]:
# what if i need 5 6 9 10
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [80]:
# fetch corner values of a2
# using ::2 -> helps in fetching alternate rows and columns ( 1 element gap in between ) like 1 , 2skip , 3 , 4skip, etcc.... ::3 -> 2 element gap in between
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [78]:
# get 1 3 9 11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [79]:
# fetch 4 7
a2[1,::3]

array([4, 7])

In [82]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [84]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
# from a3 , find middle one array
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [86]:
# except middle one
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [87]:
# fetch first matrix's second row
a3[0,1,:]

array([3, 4, 5])

## ITERATING

In [ ]:
print(f"a1:\n{a1}\n")
print(f"a2:\n{a2}\n")
print(f"a3:\n{a3}\n")

a1:
[0 1 2 3 4 5 6 7 8 9]

a2:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a3:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]



In [92]:
# iterating on a1
for i in a1:
  print(i)

# for 1D array , every element is considered as single printable entity

0
1
2
3
4
5
6
7
8
9


In [93]:
# iterating on a2
for i in a2:
  print(i)

# for 2D array , every 1D array is considered as single printable entity linewise

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [94]:
# iterating on a3
for i in a3:
  print(i)

# for 3D array , every 2D array inside is considered as single printable entity linewise

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [95]:
# how to iterate to each and every element for nD array?
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


##RESHAPING

In [96]:
# reshaping we were using all along in this notebook
# transposing array:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [97]:
# another syntax for transposing
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [98]:
# ravel -> convert any dimention array into 1D array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

##STACKING

In [100]:
# horizontal stacking -> 2x2 & 2x2 array , after horizontal stacking it will become 2x4 array
# vertical stacking -> 2x2 & 2x2 array , after horizontal stacking it will become 4x2 array
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [101]:
print(a4,"\n")
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [102]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [103]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [104]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

##SPLITTING

In [105]:
# horizontal split -> when cutting vertically
# vertical split -> when cutting horizontally
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
np.hsplit(a4,2) # split in two equal parts

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [107]:
np.vsplit(a4,3) # split in three equal parts

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]