**ADVANCE NUMPY TOPICS**

##Numpy Arrays vs Python Lists

In [9]:
# SPEED: Which is faster
# we will create 2 list and add each of its element and store in c list. Similarly, this will be done using np also and we will compare the time of completion
import time


a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
start = time.time()
for i in range(len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)


1.8259940147399902


In [10]:
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a+b

print(time.time()-start)

0.2998819351196289


numpy array won and its ~40 times faster than python lists

In [11]:
# Memory
#lists
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [12]:
# np arrays
a = np.arange(10000000,dtype = np.int32)
sys.getsizeof(a)

40000112

honestly both take similar space but we can change the dtype of numpy as per the requirements

In [13]:
# convinience: numpy is much more convinient then python

In [14]:
# storing non homogeneous data:
# we can't store non homogenous data in numpy list. But its possible in python lists.

##Advanced Indexing

In [19]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
# Fancy Indexing -> we pass the list of number and those number represent index of rows
# this get majorly used in pandas
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [23]:
# another example , when we need selective columns
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [29]:
# Boolean Indexing -> when we need to extract using a logic (eg: extract all even numbers , its a logic not a selection of rows by user.)
# Its super important and very useful
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

# NOTE: randint is mainly for extracting number in perticular range, like np.random.randint(range of start and end, how many number needed)

array([[14, 41, 77, 54],
       [43, 41, 45, 78],
       [46, 59, 43, 53],
       [87, 69, 86, 78],
       [14, 62, 50, 34],
       [ 2,  2, 44, 43]])

In [31]:
# find all numbers greater than 50
a > 50

array([[False, False,  True,  True],
       [False, False, False,  True],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [False, False, False, False]])

In [32]:
# write way to filter out in boolean indexing
a[a>50]

array([77, 54, 78, 59, 53, 87, 69, 86, 78, 62])

In [33]:
# find out even numbers
a[a % 2 == 0]

array([14, 54, 78, 46, 86, 78, 14, 62, 50, 34,  2,  2, 44])

In [36]:
# find all numbers which are greater than 50 and even in nature
a[(a % 2 == 0) & (a > 50)]

array([54, 78, 86, 78, 62])

In [37]:
# find all numbers which are NOT divisible by 7
a[~(a % 7 == 0)]

array([41, 54, 43, 41, 45, 78, 46, 59, 43, 53, 87, 69, 86, 78, 62, 50, 34,
        2,  2, 44, 43])