#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
!pip install numpy

In [3]:
# np is just a alias for numpy
import numpy as np

# creating array using numpy

# 1D
arr_1d = np.array([1,2,3])
print(f"1D array : {arr_1d}")
print(type(arr_1d))
print(arr_1d.shape) #-> single dimension thats why only one number available : 3,

1D array : [1 2 3]
<class 'numpy.ndarray'>
(3,)


In [4]:
arr_2d = arr_1d
arr_2d.reshape(1,3)
print(arr_2d)
print(arr_2d.shape)
# -> this is called reshaping 1D into 2D 
# main differentiator is double brackets on opening and closing [[...],[...]] its a nested list

[1 2 3]
(3,)


In [5]:
# 2D array
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
# np.arrange(start,end,stepsize)
# start including , end excluding 
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
# np.ones() -> need tuple as input 
# np.ones((rows,cols))
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# identity matrix  -> diagnal elements 1, remaining 0
# always square matrix soo single value as input
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# Attributes of numpy
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape: ",arr.shape)
print("Number of dimensions: ",arr.ndim)
print("Size (number of elements): ", arr.size)
print("Dtype: ",arr.dtype)
print("Item Size (in bytes): ",arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Dtype:  int64
Item Size (in bytes):  8


In [27]:
arr_mem = np.arange(10,dtype=np.int32)
arr_mem.dtype

dtype('int32')

In [28]:
# astype -> change the datatype
arr_mem.astype(np.int64)
arr_mem.dtype

dtype('int32')

In [30]:
# astype() does NOT modify the original array.
# Instead, it creates and returns a new array with the new datatype.
# thats why above didn't changed
# storing it maked change
arr_mem_64 = arr_mem.astype(np.int64)
arr_mem_64.dtype


dtype('int64')

In [32]:
# Numpy Vectorize operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

In [34]:
# element wise addition -> simply add arrays 
arr1+arr2

array([11, 22, 33, 44, 55])

In [35]:
# element wise subtraction
arr1-arr2

array([ -9, -18, -27, -36, -45])

In [36]:
arr2-arr1

array([ 9, 18, 27, 36, 45])

In [37]:
# element wise multiplication and division

print(arr1*arr2, "\n")
print(arr1/arr2)

[ 10  40  90 160 250] 

[0.1 0.1 0.1 0.1 0.1]


In [38]:
# universal function -> functions which applies to the entire array
arr = np.array([2,3,4,5,6])

In [40]:
# squareroot
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [42]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
# array slicing and indexing
arr[0]

array([1, 2, 3, 4])

In [44]:
arr[0][3]

np.int64(4)

In [45]:
arr[2:]

array([[ 9, 10, 11, 12]])

In [46]:
arr[1:][2:]

array([], shape=(0, 4), dtype=int64)

In [48]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [51]:
print(arr[0:2,2:4])

[[3 4]
 [7 8]]


In [52]:
print(arr[1:3,1:3])

[[ 6  7]
 [10 11]]


In [53]:
# modifying arr elements
arr[0,0] = 100

In [54]:
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [59]:
# some practical applications wrt arrays

# 1. statistical concept -> normalization
# make data to have mean=0 and standard deviation = 1

data = np.arange(1,6)
print(data)

# calculate mean and sd
mean = np.mean(data)
std = np.std(data)

# normalize the data
normalized_data = (data - mean)/std
print("Normalized data: ",normalized_data)

[1 2 3 4 5]
Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [60]:
# other
np.median(data)

np.float64(3.0)

In [61]:
np.var(data)

np.float64(2.0)

In [66]:
# Logical operations

data = np.arange(1,11)

data[(data>5) & (data<8)]

array([6, 7])