#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [2]:
# np is just a alias for numpy
import numpy as np

In [3]:
# creating array using numpy

# 1D
# we pass the list when use np.array(inside here)
arr_1d = np.array([1,2,3])
print(f"1D array : {arr_1d}")
print(type(arr_1d))
print(arr_1d.shape) #-> single dimension thats why only one number available : 3,

1D array : [1 2 3]
<class 'numpy.ndarray'>
(3,)


In [4]:
# reshaping 1d array into 2d
# main differentiator is double brackets on opening and closing [[...],[...]] its a nested list

arr_2d = arr_1d.reshape(1,3)
print(arr_2d)
print(arr_2d.shape)
# -> this is called reshaping 1D into 2D 

[[1 2 3]]
(1, 3)


In [5]:
# 2D array
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)
print(arr_2d.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [6]:
# np.arrange(start,end,stepsize)
# start including , end excluding 
# fill up the number from start to end-1
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [53]:
# np.random -> initialize with random values between 0 and 1
np.random.random((3,4))

# why two randoms? -> because random is a class and it has a method named random ( concept of OOPS )

array([[0.68887822, 0.91821345, 0.3343867 , 0.2499656 ],
       [0.9138182 , 0.58745289, 0.03635913, 0.02753423],
       [0.51292035, 0.17017158, 0.89094944, 0.09373661]])

In [7]:
# random values in array
# np.random.randint make you able to choose random values from a range 
# we can also provide the size parameter here
arr_rand = np.random.randint(1,21)
arr_rand2 = np.random.randint(1,11, size=(3,8))

print(arr_rand)
print(arr_rand2)

8
[[ 3  5  2  3 10  9  5  5]
 [ 9  5  5  2 10  4  3  2]
 [ 1  3  2  6  2  4  8  8]]


In [8]:
# np.ones() -> need tuple as input 
# np.ones((rows,cols))
all_1_arr = np.ones((3,4))
all_1_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# diagonal elements filling
# passing parameters (array,value) -> value with which you want to replace
np.fill_diagonal(all_1_arr,0)
all_1_arr

array([[0., 1., 1., 1.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.]])

In [10]:
# trying to use fill_diagonal with 1d array
# for 1D array its not possible !!!
# minimum of 2D array is needed
try:
    np.fill_diagonal(arr_1d,0)

except Exception as ex:
    print(ex)

array must be at least 2-d


In [11]:
np.fill_diagonal(arr_2d,1)
arr_2d

array([[1, 2, 3, 4],
       [5, 1, 7, 8]])

In [12]:
# identity matrix  -> diagnal elements 1, remaining 0
# always square matrix soo single value as input
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
# np.linspace -> helps in generating the values within a range where lowerbound and upperbound are inclusive/included.
# ALSO, all the elements generated are linearly gapped
# np.linspace(lowerbound, upperbound, number of elements)
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
# Attributes of numpy
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape: ",arr.shape)
print("Number of dimensions: ",arr.ndim)
print("Size (number of elements): ", arr.size)
print("Dtype: ",arr.dtype)
print("Item Size (in bytes): ",arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Dtype:  int64
Item Size (in bytes):  8


In [14]:
arr_mem = np.arange(10,dtype=np.int32)
arr_mem.dtype

dtype('int32')

In [15]:
# astype -> change the datatype
arr_mem.astype(np.int64)
arr_mem.dtype

dtype('int32')

In [16]:
# astype() does NOT modify the original array.
# Instead, it creates and returns a new array with the new datatype.
# thats why above didn't changed
# storing it maked change
arr_mem_64 = arr_mem.astype(np.int64)
arr_mem_64.dtype


dtype('int64')

In [57]:
# itemsize -> how much space array is occupying in memory and give output in bytes
print(arr.itemsize)

print("\nNOTE:int32 take 4bytes and int64 take 8bytes")

8

NOTE:int32 take 4bytes and int64 take 8bytes


In [17]:
# Numpy Vectorize operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

In [18]:
# element wise addition -> simply add arrays 
arr1+arr2

array([11, 22, 33, 44, 55])

In [19]:
# element wise subtraction
arr1-arr2

array([ -9, -18, -27, -36, -45])

In [20]:
arr2-arr1

array([ 9, 18, 27, 36, 45])

In [21]:
# element wise multiplication and division

print(arr1*arr2, "\n")
print(arr1/arr2)

[ 10  40  90 160 250] 

[0.1 0.1 0.1 0.1 0.1]


In [22]:
# universal function -> functions which applies to the entire array
arr = np.array([2,3,4,5,6])

In [23]:
# squareroot
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
# Indexing -> accessing the element of array
# positive indexing ( from left to right ) starts with 0
# negative indexing ( from right to left ) starts with -1
# An nD array is made up of two or more (n-1)D arrays. Example: 3D array is made up of 2 2D arrays.
# An nD array needs n number in input to fetch element. Example: 1D array need 1 value to fetch , 3D array needs 3 values

In [25]:
# array slicing and indexing
arr[0]

array([1, 2, 3, 4])

In [26]:
arr[0][3]

np.int64(4)

In [27]:
arr[2:]

array([[ 9, 10, 11, 12]])

In [28]:
arr[1:][2:]

array([], shape=(0, 4), dtype=int64)

In [29]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [30]:
print(arr[0:2,2:4])

[[3 4]
 [7 8]]


In [31]:
print(arr[1:3,1:3])

[[ 6  7]
 [10 11]]


In [32]:
# modifying arr elements
arr[0,0] = 100

In [33]:
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


#### ITERATING

In [60]:
# creating 3 arrays for further use
# a1 is a array/vector , a2 is a matrix , a3 is like a tensor or 3D tensor
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [61]:
print(f"a1:\n{a1}\n")
print(f"a2:\n{a2}\n")
print(f"a3:\n{a3}\n")

a1:
[0 1 2 3 4 5 6 7 8 9]

a2:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

a3:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [62]:
# iterating on a1
for i in a1:
  print(i)

# for 1D array , every element is considered as single printable entity

0
1
2
3
4
5
6
7
8
9


In [63]:
# iterating on a2
for i in a2:
  print(i)

# for 2D array , every 1D array is considered as single printable entity linewise

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [64]:
# iterating on a3
for i in a3:
  print(i)

# for 3D array , every 2D array inside is considered as single printable entity linewise

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
# how to iterate to each and every element for nD array?
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [34]:
# some practical applications wrt arrays

# 1. statistical concept -> normalization
# make data to have mean=0 and standard deviation = 1

data = np.arange(1,6)
print(data)

# calculate mean and sd
mean = np.mean(data)
std = np.std(data)

# normalize the data
normalized_data = (data - mean)/std
print("Normalized data: ",normalized_data)

[1 2 3 4 5]
Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [35]:
# other
np.median(data)

np.float64(3.0)

In [36]:
np.var(data)

np.float64(2.0)

In [37]:
# Logical operations

data = np.arange(1,11)

data[(data>5) & (data<8)]

array([6, 7])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [38]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [39]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print()
print(b)
print()
print(a+b)

[[0 1 2]
 [3 4 5]]

[[0 1 2]]

[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [40]:
# more examples
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
b = np.arange(3)
b

array([0, 1, 2])

In [42]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [ ]:
# but if we try to do like below 
a = np.arange(12).reshape(4,3)
b = np.arange(11)
a+b

In [47]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [48]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a,'\n')
print(b,'\n')

print(a + b)

[[0 1 2]] 

[[0]
 [1]
 [2]
 [3]] 

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [49]:
a = np.array([1])
print(f"array a: \n{a}")

b = np.arange(4).reshape(2,2)
print(f"array b: \n{b}")
print("\na+b:")
print(a+b)

array a: 
[1]
array b: 
[[0 1]
 [2 3]]

a+b:
[[1 2]
 [3 4]]


In [52]:
try:
    a = np.arange(16).reshape(4,4)
    b = np.arange(4).reshape(2,2)

    print(f"a: \n{a}")
    print(f"b: \n{b}")

    print(a+b)

except Exception as ex:
    print(ex)

a: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b: 
[[0 1]
 [2 3]]
operands could not be broadcast together with shapes (4,4) (2,2) 
